update Chirpy Jekyll 5.6.1

diff --git a/tools/release b/tools/release
--- a/tools/release
+++ b/tools/release
@@ -14,7 +14,8 @@
 
 set -eu
 
-opt_pre=false # preview mode option
+opt_pre=false      # preview mode option
+opt_skip_ver=false # option for skip versioning
 
 working_branch="$(git branch --show-current)"
 
@@ -26,9 +27,11 @@ GEM_SPEC="jekyll-theme-chirpy.gemspec"
 
 NODE_CONFIG="package.json"
 
+JS_DIST="assets/js/dist"
+BACKUP_PATH="$(mktemp -d)"
+
 FILES=(
   "_sass/jekyll-theme-chirpy.scss"
-  "_javascript/copyright"
   "$GEM_SPEC"
   "$NODE_CONFIG"
 )
@@ -48,6 +51,7 @@ help() {
   echo "   bash ./tools/release.sh [options]"
   echo
   echo "Options:"
+  echo "     -k, --skip-versioning    Skip the step of generating the version number."
   echo "     -p, --preview            Enable preview mode, only package, and will not modify the branches"
   echo "     -h, --help               Print this information."
 }
@@ -67,17 +71,24 @@ _check_git() {
 }
 
 _check_src() {
-  if [[ ! -f $1 && ! -d $1 ]]; then
-    echo -e "Error: Missing file \"$1\"!\n"
-    exit 1
-  fi
+  for i in "${!FILES[@]}"; do
+    _src="${FILES[$i]}"
+    if [[ ! -f $_src && ! -d $_src ]]; then
+      echo -e "Error: Missing file \"$_src\"!\n"
+      exit 1
+    fi
+  done
+
 }
 
 _check_command() {
-  if ! command -v "$1" &>/dev/null; then
-    echo "Command '$1' not found"
-    exit 1
-  fi
+  for i in "${!TOOLS[@]}"; do
+    cli="${TOOLS[$i]}"
+    if ! command -v "$cli" &>/dev/null; then
+      echo "Command '$cli' not found!"
+      exit 1
+    fi
+  done
 }
 
 _check_node_packages() {
@@ -87,25 +98,22 @@ _check_node_packages() {
 }
 
 check() {
+  _check_command
   _check_git
-
-  for i in "${!FILES[@]}"; do
-    _check_src "${FILES[$i]}"
-  done
-
-  for i in "${!TOOLS[@]}"; do
-    _check_command "${TOOLS[$i]}"
-  done
-
+  _check_src
   _check_node_packages
 }
 
-_bump_file() {
+_bump_files() {
   for i in "${!FILES[@]}"; do
+    if [[ ${FILES[$i]} == "$NODE_CONFIG" ]]; then
+      continue
+    fi
+
     sed -i "s/v[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+/v$1/" "${FILES[$i]}"
   done
 
-  npx gulp
+  npm run build
 }
 
 _bump_gemspec() {
@@ -121,7 +129,7 @@ _bump_gemspec() {
 #
 # 2. Create a commit to save the changes.
 bump() {
-  _bump_file "$1"
+  _bump_files "$1"
   _bump_gemspec "$1"
 
   if [[ $opt_pre = false && -n $(git status . -s) ]]; then
@@ -145,7 +153,10 @@ build_gem() {
   echo -e "Build the gem package for v$_version\n"
   cleanup_config
   rm -f ./*.gem
+  git add "$JS_DIST" -f # add JS dist to gem
   gem build "$GEM_SPEC"
+  cp "$JS_DIST"/* "$BACKUP_PATH"
+  git restore --staged "$JS_DIST" # resume the git status
   resume_config
 }
 
@@ -170,16 +181,21 @@ release() {
 }
 
 main() {
-  check
+  if [[ $opt_skip_ver = false ]]; then
+    check
 
-  # auto-generate a new version number to the file 'package.json'
-  if $opt_pre; then
-    standard-version --prerelease rc
-  else
-    standard-version
+    # auto-generate a new version number to the file 'package.json'
+    if $opt_pre; then
+      standard-version --prerelease rc
+    else
+      standard-version
+    fi
   fi
 
-  _version="$(grep '"version":' package.json | sed 's/.*: "//;s/".*//')"
+  # Change heading of Patch version to level 2 (a bug from `standard-version`)
+  sed -i "s/^### \[/## \[/g" CHANGELOG.md
+
+  _version="$(grep '"version":' "$NODE_CONFIG" | sed 's/.*: "//;s/".*//')"
 
   echo -e "Bump version number to $_version\n"
   bump "$_version"
@@ -192,6 +208,9 @@ main() {
   else
     release "$_version"
   fi
+
+  # restore the dist files for future development
+  mkdir -p "$JS_DIST" && cp "$BACKUP_PATH"/* "$JS_DIST"
 }
 
 while (($#)); do
@@ -199,6 +218,10 @@ while (($#)); do
   case $opt in
   -p | --preview)
     opt_pre=true
+    shift
+    ;;
+  -k | --skip-versioning)
+    opt_skip_ver=true
     shift
     ;;
   -h | --help)
